CDEV-434 Lang Parameter
Olapic/wp-plugin pull request #6
Opened 2017-12-18 18:26 UTC by robertpisano

What does this pull request do?
---------------------------------
Updates the plugin to accept the "lang" parameter in the shortcode, which maps to the data-language parameter in the olapic widget code. 

How to test this
----------------
In order to test this you'll need to be able to have access to a wordpress instance. I downloaded mamp, and downloaded wordpress, and placed the wordpress directory into the mamp/htdocs folder and logged in. 

Next you'll need to install the plugin itself - to do this you can simply place the olapic-widget.php file into the mamp/htdocs/wordpress/wp-content/plugins directory. 

Finally, you need to test it. To do this you can place the following code into a test word press page, and preview it.

```
[olapic instance-id="816c53094bf966c71780c041ba7868bf" apikey="cfa3e701a4b8d562e4b6f085b10d0e31467f6e3d4aafbd170314335c158d214c" tags="og-laura" mode="development" lang="de_DE" ]
```

You should be able to see the translated widget

Related Tickets
----------------
[CDEV-434](https://photorank.atlassian.net/browse/CDEV-434)

2017-12-18 19:00 UTC, jhankim requested changes
Few edits in the doc, after that 🚢

2017-12-18 19:00 UTC, jhankim commented on README.md
> +	* the language code that you want the widget to be translated to. This should correspond with the language code you set in the appearance section of the platform
Capitalization issues:
`the` => `The`
`appearance section` => `Appearance Editor`
`platform` => `platform.`

Consider using the same language from the lang section in the platform:
> The naming convention for the language's name is based on the ISO-639 language code (e.g. pt for Portuguese) followed by the ISO-3166 country code (e.g. _PT for Portugal or _BR for Brazil).

2017-12-20 12:15 UTC, emidaniele commented on olapic-widget/olapic-widget.php
> +    //since data-tags, data-lang and data-mode aren't required, checks if its empty before giving it a value
Any particular reason to have this comment below the actual line of code?

2017-12-20 12:15 UTC, emidaniele approved these changes
Just a minor comment.
:shipit:

2017-12-20 15:13 UTC, jhankim approved these changes

2017-12-20 19:55 UTC, merged